package com.yxp.yunstore_common.model.material;

import com.yxp.yunstore_common.model.base.BaseMaterialVideo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MaterialVideo extends BaseMaterialVideo<MaterialVideo> {
	
	public static final MaterialVideo dao = new MaterialVideo().dao();
}
