package com.yxp.yunstore_common.model.material;

import com.yxp.yunstore_common.model.base.BaseMaterialPicture;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MaterialPicture extends BaseMaterialPicture<MaterialPicture> {
	
	public static final MaterialPicture dao = new MaterialPicture().dao();
}
