package com.yxp.yunstore_common.model.order;

import com.yxp.yunstore_common.model.base.BaseTraderOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TraderOrder extends BaseTraderOrder<TraderOrder> {
	
	public static final TraderOrder dao = new TraderOrder().dao();
}
