package com.yxp.yunstore_common.model.system;

import com.yxp.yunstore_common.model.base.BaseSystemOperLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemOperLog extends BaseSystemOperLog<SystemOperLog> {
	
	public static final SystemOperLog dao = new SystemOperLog().dao();
}
