package com.yxp.yunstore_common.model.system;

import com.yxp.yunstore_common.model.base.BaseSystemRegion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemToken extends BaseSystemRegion<SystemToken> {
	
	public static final SystemToken dao = new SystemToken().dao();
}
