package com.yxp.yunstore_common.model.system;

import com.yxp.yunstore_common.model.base.BaseSystemRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemRole extends BaseSystemRole<SystemRole> {
	
	public static final SystemRole dao = new SystemRole().dao();
}
