package com.yxp.yunstore_common.model.system;

import com.yxp.yunstore_common.model.base.BaseSystemAdminInvalid;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemAdminInvalid extends BaseSystemAdminInvalid<SystemAdminInvalid> {
	
	public static final SystemAdminInvalid dao = new SystemAdminInvalid().dao();
	
}
