package com.yxp.yunstore_common.model.system;

import com.yxp.yunstore_common.model.base.BaseSystemRoleOperRef;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemRoleOperRef extends BaseSystemRoleOperRef<SystemRoleOperRef> {
	
	public static final SystemRoleOperRef dao = new SystemRoleOperRef().dao();
}
