package com.yxp.yunstore_common.model.system;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemMenu extends BaseSystemMenu<SystemMenu> {
	
	public static final SystemMenu dao = new SystemMenu().dao();
}
