package com.yxp.yunstore_common.model.system;

import com.yxp.yunstore_common.model.base.BaseSystemNotice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemNotice extends BaseSystemNotice<SystemNotice> {
	
	public static final SystemNotice dao = new SystemNotice().dao();
}
