package com.yxp.yunstore_common.model.system;

import com.yxp.yunstore_common.model.base.BaseSystemOper;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemOper extends BaseSystemOper<SystemOper> {
	
	public static final SystemOper dao = new SystemOper().dao();
}
