package com.yxp.yunstore_common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;
import com.yxp.yunstore_common.model.doc.DocNoteBook;
import com.yxp.yunstore_common.model.doc.DocNoteinfo;
import com.yxp.yunstore_common.model.label.LabelInfo;
import com.yxp.yunstore_common.model.material.MaterialPicture;
import com.yxp.yunstore_common.model.material.MaterialVideo;
import com.yxp.yunstore_common.model.order.TraderOrder;
import com.yxp.yunstore_common.model.system.SystemAdmin;
import com.yxp.yunstore_common.model.system.SystemAdminInvalid;
import com.yxp.yunstore_common.model.system.SystemMenu;
import com.yxp.yunstore_common.model.system.SystemNotice;
import com.yxp.yunstore_common.model.system.SystemOper;
import com.yxp.yunstore_common.model.system.SystemOperLog;
import com.yxp.yunstore_common.model.system.SystemRegion;
import com.yxp.yunstore_common.model.system.SystemRole;
import com.yxp.yunstore_common.model.system.SystemRoleOperRef;
import com.yxp.yunstore_common.model.system.SystemToken;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("doc_noteinfo", "id", DocNoteinfo.class);
		arp.addMapping("system_admin", "id", SystemAdmin.class);
		arp.addMapping("system_admin_invalid", SystemAdminInvalid.class);
		arp.addMapping("system_region", "id", SystemRegion.class);
		arp.addMapping("system_token", SystemToken.class);
		arp.addMapping("system_role", SystemRole.class);
		arp.addMapping("system_role_oper_ref", SystemRoleOperRef.class);
		arp.addMapping("system_menu", SystemMenu.class);
		arp.addMapping("system_oper", SystemOper.class);
		arp.addMapping("system_oper_log", SystemOperLog.class);
		arp.addMapping("material_picture", MaterialPicture.class);
		arp.addMapping("material_video", MaterialVideo.class);
		arp.addMapping("system_notice", SystemNotice.class);
		arp.addMapping("doc_notebook", DocNoteBook.class);
		arp.addMapping("label_info", LabelInfo.class);
		arp.addMapping("trader_order", TraderOrder.class);
	}
}

