package com.yxp.yunstore_common.model;

import com.yxp.yunstore_common.model.base.BaseSystemAdmin;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemAdmin extends BaseSystemAdmin<SystemAdmin> {
	
	public static final SystemAdmin dao = new SystemAdmin().dao();
	
}
