package com.yxp.yunstore_common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSystemAdmin<M extends BaseSystemAdmin<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 用户编号，自动生成，总部账户编号为空，代理账户编号以上级编号+“.”+（下级个数+1）
	 */
	public void setCode(java.lang.String code) {
		set("code", code);
	}
	
	/**
	 * 用户编号，自动生成，总部账户编号为空，代理账户编号以上级编号+“.”+（下级个数+1）
	 */
	public java.lang.String getCode() {
		return getStr("code");
	}

	/**
	 * 用户类型，1：总部账户，2：代理账户
	 */
	public void setUserType(java.lang.Integer userType) {
		set("user_type", userType);
	}
	
	/**
	 * 用户类型，1：总部账户，2：代理账户
	 */
	public java.lang.Integer getUserType() {
		return getInt("user_type");
	}

	/**
	 * 登录名
	 */
	public void setLoginName(java.lang.String loginName) {
		set("login_name", loginName);
	}
	
	/**
	 * 登录名
	 */
	public java.lang.String getLoginName() {
		return getStr("login_name");
	}

	/**
	 * 真实姓名
	 */
	public void setRealName(java.lang.String realName) {
		set("real_name", realName);
	}
	
	/**
	 * 真实姓名
	 */
	public java.lang.String getRealName() {
		return getStr("real_name");
	}

	/**
	 * 密码
	 */
	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	/**
	 * 密码
	 */
	public java.lang.String getPassword() {
		return getStr("password");
	}

	/**
	 * 密码加密hash
	 */
	public void setEncrypt(java.lang.String encrypt) {
		set("encrypt", encrypt);
	}
	
	/**
	 * 密码加密hash
	 */
	public java.lang.String getEncrypt() {
		return getStr("encrypt");
	}

	/**
	 * 角色id
	 */
	public void setRoleId(java.lang.Integer roleId) {
		set("role_id", roleId);
	}
	
	/**
	 * 角色id
	 */
	public java.lang.Integer getRoleId() {
		return getInt("role_id");
	}

	/**
	 * 上级id
	 */
	public void setParentId(java.lang.Integer parentId) {
		set("parent_id", parentId);
	}
	
	/**
	 * 上级id
	 */
	public java.lang.Integer getParentId() {
		return getInt("parent_id");
	}

	/**
	 * 是否禁用
	 */
	public void setDisabledFlag(java.lang.Integer disabledFlag) {
		set("disabled_flag", disabledFlag);
	}
	
	/**
	 * 是否禁用
	 */
	public java.lang.Integer getDisabledFlag() {
		return getInt("disabled_flag");
	}

	/**
	 * 最后登录ip
	 */
	public void setLastLoginIp(java.lang.String lastLoginIp) {
		set("last_login_ip", lastLoginIp);
	}
	
	/**
	 * 最后登录ip
	 */
	public java.lang.String getLastLoginIp() {
		return getStr("last_login_ip");
	}

	/**
	 * 最后登录时间
	 */
	public void setLastLoginTime(java.util.Date lastLoginTime) {
		set("last_login_time", lastLoginTime);
	}
	
	/**
	 * 最后登录时间
	 */
	public java.util.Date getLastLoginTime() {
		return get("last_login_time");
	}

	/**
	 * 是否超级管理员
	 */
	public void setSuperFlag(java.lang.Integer superFlag) {
		set("super_flag", superFlag);
	}
	
	/**
	 * 是否超级管理员
	 */
	public java.lang.Integer getSuperFlag() {
		return getInt("super_flag");
	}

	/**
	 * 手机号
	 */
	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}
	
	/**
	 * 手机号
	 */
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	/**
	 * 登录错误次数，超过3次登录时要出现验证码
	 */
	public void setLoginError(java.lang.Integer loginError) {
		set("login_error", loginError);
	}
	
	/**
	 * 登录错误次数，超过3次登录时要出现验证码
	 */
	public java.lang.Integer getLoginError() {
		return getInt("login_error");
	}

	public void setCountyName(java.lang.String countyName) {
		set("county_name", countyName);
	}
	
	public java.lang.String getCountyName() {
		return getStr("county_name");
	}

	public void setCountyCode(java.lang.String countyCode) {
		set("county_code", countyCode);
	}
	
	public java.lang.String getCountyCode() {
		return getStr("county_code");
	}

	public void setCityName(java.lang.String cityName) {
		set("city_name", cityName);
	}
	
	public java.lang.String getCityName() {
		return getStr("city_name");
	}

	/**
	 * 市
	 */
	public void setCityCode(java.lang.String cityCode) {
		set("city_code", cityCode);
	}
	
	/**
	 * 市
	 */
	public java.lang.String getCityCode() {
		return getStr("city_code");
	}

	/**
	 * 省名称
	 */
	public void setProvinceName(java.lang.String provinceName) {
		set("province_name", provinceName);
	}
	
	/**
	 * 省名称
	 */
	public java.lang.String getProvinceName() {
		return getStr("province_name");
	}

	/**
	 * 省编码
	 */
	public void setProvinceCode(java.lang.String provinceCode) {
		set("province_code", provinceCode);
	}
	
	/**
	 * 省编码
	 */
	public java.lang.String getProvinceCode() {
		return getStr("province_code");
	}

	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	/**
	 * 创建时间
	 */
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatedAt() {
		return get("created_at");
	}

	/**
	 * 更新时间
	 */
	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdatedAt() {
		return get("updated_at");
	}

}
