package com.yxp.yunstore_common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDocNoteinfo<M extends BaseDocNoteinfo<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 笔记本id
	 */
	public void setNotebookId(java.lang.Integer notebookId) {
		set("notebook_id", notebookId);
	}
	
	/**
	 * 笔记本id
	 */
	public java.lang.Integer getNotebookId() {
		return getInt("notebook_id");
	}

	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	/**
	 * 标题
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	/**
	 * 标题
	 */
	public java.lang.String getTitle() {
		return getStr("title");
	}

	/**
	 * 笔记内容
	 */
	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	/**
	 * 笔记内容
	 */
	public java.lang.String getContent() {
		return getStr("content");
	}

	/**
	 * 创建时间
	 */
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatedAt() {
		return get("created_at");
	}

	/**
	 * 更新时间
	 */
	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdatedAt() {
		return get("updated_at");
	}

}
