package com.yxp.yunstore_common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDocNoteBook<M extends BaseDocNoteBook<M>> extends Model<M> implements IBean {

}
