package com.yxp.yunstore_common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSystemAdminInvalid<M extends BaseSystemAdminInvalid<M>> extends Model<M> implements IBean {

	/**
	 * 用户编号，自动生成
	 */
	public void setCode(java.lang.String code) {
		set("code", code);
	}
	
	/**
	 * 用户编号，自动生成
	 */
	public java.lang.String getCode() {
		return getStr("code");
	}

	/**
	 * 用户类型
	 */
	public void setUserType(java.lang.Integer userType) {
		set("user_type", userType);
	}
	
	/**
	 * 用户类型
	 */
	public java.lang.Integer getUserType() {
		return getInt("user_type");
	}

	/**
	 * 登录名
	 */
	public void setLoginName(java.lang.String loginName) {
		set("login_name", loginName);
	}
	
	/**
	 * 登录名
	 */
	public java.lang.String getLoginName() {
		return getStr("login_name");
	}

	/**
	 * 真实姓名
	 */
	public void setRealName(java.lang.String realName) {
		set("real_name", realName);
	}
	
	/**
	 * 真实姓名
	 */
	public java.lang.String getRealName() {
		return getStr("real_name");
	}

	/**
	 * 密码
	 */
	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	/**
	 * 密码
	 */
	public java.lang.String getPassword() {
		return getStr("password");
	}

	/**
	 * 密码加密salt
	 */
	public void setSalt(java.lang.String salt) {
		set("salt", salt);
	}
	
	/**
	 * 密码加密salt
	 */
	public java.lang.String getSalt() {
		return getStr("salt");
	}

	/**
	 * 角色id
	 */
	public void setRoleId(java.lang.Integer roleId) {
		set("role_id", roleId);
	}
	
	/**
	 * 角色id
	 */
	public java.lang.Integer getRoleId() {
		return getInt("role_id");
	}

	/**
	 * 上级id
	 */
	public void setParentId(java.lang.Integer parentId) {
		set("parent_id", parentId);
	}
	
	/**
	 * 上级id
	 */
	public java.lang.Integer getParentId() {
		return getInt("parent_id");
	}

	/**
	 * 是否禁用
	 */
	public void setDisabledFlag(java.lang.Integer disabledFlag) {
		set("disabled_flag", disabledFlag);
	}
	
	/**
	 * 是否禁用
	 */
	public java.lang.Integer getDisabledFlag() {
		return getInt("disabled_flag");
	}

	/**
	 * 最后登录ip
	 */
	public void setLastLoginIp(java.lang.String lastLoginIp) {
		set("last_login_ip", lastLoginIp);
	}
	
	/**
	 * 最后登录ip
	 */
	public java.lang.String getLastLoginIp() {
		return getStr("last_login_ip");
	}

	/**
	 * 最后登录时间
	 */
	public void setLastLoginTime(java.util.Date lastLoginTime) {
		set("last_login_time", lastLoginTime);
	}
	
	/**
	 * 最后登录时间
	 */
	public java.util.Date getLastLoginTime() {
		return get("last_login_time");
	}

	/**
	 * 是否超级管理员
	 */
	public void setSuperFlag(java.lang.Integer superFlag) {
		set("super_flag", superFlag);
	}
	
	/**
	 * 是否超级管理员
	 */
	public java.lang.Integer getSuperFlag() {
		return getInt("super_flag");
	}

	/**
	 * 手机号
	 */
	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}
	
	/**
	 * 手机号
	 */
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	/**
	 * 登录错误次数
	 */
	public void setLoginError(java.lang.Integer loginError) {
		set("login_error", loginError);
	}
	
	/**
	 * 登录错误次数
	 */
	public java.lang.Integer getLoginError() {
		return getInt("login_error");
	}

	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	/**
	 * 头像
	 */
	public void setHeadUrl(java.lang.String headUrl) {
		set("head_url", headUrl);
	}
	
	/**
	 * 头像
	 */
	public java.lang.String getHeadUrl() {
		return getStr("head_url");
	}

	/**
	 * 性别
	 */
	public void setGender(java.lang.Integer gender) {
		set("gender", gender);
	}
	
	/**
	 * 性别
	 */
	public java.lang.Integer getGender() {
		return getInt("gender");
	}

	/**
	 * 创建时间
	 */
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatedAt() {
		return get("created_at");
	}

	/**
	 * 更新时间
	 */
	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdatedAt() {
		return get("updated_at");
	}
	
}
