package com.yxp.yunstore_common.model.label;

import com.yxp.yunstore_common.model.base.BaseLabelInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LabelInfo extends BaseLabelInfo<LabelInfo> {
	
	public static final LabelInfo dao = new LabelInfo().dao();
}
